runtime: python310

env_variables:
  PROJECT_ID: "envirolens"
  BILLING_ACCOUNT_ID: "016329-5C3F2B-865160"
  GCP_BUCKET_NAME: "lensbuck"
  GEMINI_API_KEY: "AIzaSyBI5tzubGAJjD-VyhkQd1xGUBgV8YCToYs"
  GOOGLE_APPLICATION_CREDENTIALS: "/app/credentials/envirolens-92dd28f73786.json"

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

instance_class: F2
